version: '3.8'

services:
  # Auth Service
  auth-service:
    build: 
      context: ./qauth
      dockerfile: Dockerfile
    container_name: auth-service
    ports:
      - "8080:8080"
    env_file:
      - ./qauth/.env
    depends_on:
      - mongodb
      - redis
    networks:
      - backend-network

  # Gateway Service
  gateway-service:
    build:
      context: ./qgateway
      dockerfile: Dockerfile
    container_name: gateway-service
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - AUTH_SERVICE_URL=http://auth-service:8080
      - USER_SERVICE_URL=http://user-service:8081
      - AUTH_SERVICE_TIMEOUT=5000
      - USER_SERVICE_TIMEOUT=5000
      - NODE_ENV=development
      - THROTTLE_TTL=60
      - THROTTLE_LIMIT=10
    depends_on:
      - auth-service
      - user-service
    networks:
      - backend-network

  # User Service
  user-service:
    build:
      context: ./quser
      dockerfile: Dockerfile
    container_name: user-service
    ports:
      - "8081:8081"
    env_file:
      - ./quser/.env
    depends_on:
      - mongodb
    networks:
      - backend-network

  # MongoDB
  mongodb:
    image: mongo:latest
    container_name: auth-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - backend-network

  # Redis
  redis:
    image: redis:latest
    container_name: auth-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend-network

volumes:
  mongodb_data:
  redis_data:

networks:
  backend-network:
    driver: bridge